-- =====================================================================
-- baseline 스키마 (잠정)
-- TODO(team): anonymous_board_erd.html이 아직 반영되지 않았다. ERD 확정 시 baseline-v2로 올린다.
-- 기준: CLAUDE.md 잠정 스키마 (2회차 시드 표 + v3 초안의 users) + 대댓글(comments.parent_id, 팀 합의)
--
-- - PK는 bigint 시퀀스(GENERATED BY DEFAULT AS IDENTITY). event_id만 UUID.
--   시드가 id를 직접 넣었다면 적재 후 setval로 시퀀스를 맞춰야 한다.
-- - 카운터는 posts가 아니라 post_stats(1:1)에서 갱신한다.
-- - 인덱스: baseline은 조회 인덱스 없이 측정한다. 이 파일에는 PK, UNIQUE(정합성 제약), FK만 둔다.
--   PostgreSQL은 PK와 UNIQUE 제약에 인덱스를 자동으로 만든다. UNIQUE는 ON CONFLICT 멱등 처리에 필요해서 뺄 수 없다.
--   FK 컬럼에는 인덱스가 자동으로 생기지 않는다.
-- - 시간 컬럼: 수정될 수 있는 테이블(boards, users, posts, comments)은 created_at + updated_at,
--   추가만 하는 테이블(post_likes, post_view_events)은 created_at만, 카운터 테이블(post_stats)은 없음.
--   JPA 저장은 Auditing이 채우고, SQL로 직접 넣는 행(시드, 네이티브 INSERT)은 DEFAULT now()로 채워진다.
-- - TODO(team): FK 제약 포함 여부 미정. 잠정으로 포함한다 (README "팀 확인 필요").
-- =====================================================================

CREATE TABLE boards (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(100) NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname   varchar(50) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE posts (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id   bigint       NOT NULL,
    author_id  bigint       NOT NULL,
    title      varchar(200) NOT NULL,
    content    text         NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_posts_board  FOREIGN KEY (board_id)  REFERENCES boards (id),
    CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES users (id)
);

-- posts와 1:1. 조회수와 좋아요 카운터는 여기서 UPDATE ... SET x = x + 1로 갱신한다 (핫 로우 경합을 일부러 둔다)
CREATE TABLE post_stats (
    post_id    bigint PRIMARY KEY,
    view_count bigint NOT NULL DEFAULT 0,
    like_count bigint NOT NULL DEFAULT 0,
    CONSTRAINT fk_post_stats_post FOREIGN KEY (post_id) REFERENCES posts (id)
);

-- parent_id가 NULL이면 댓글, 값이 있으면 대댓글이다. 깊이는 1단계만 허용한다(대댓글에 답글 금지).
-- 깊이 제한과 "부모는 같은 게시글의 댓글" 규칙은 DB 제약으로 표현하기 어려워 서비스에서 검증한다.
CREATE TABLE comments (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint      NOT NULL,
    user_id    bigint      NOT NULL,
    parent_id  bigint,
    content    text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_comments_post   FOREIGN KEY (post_id)   REFERENCES posts (id),
    CONSTRAINT fk_comments_user   FOREIGN KEY (user_id)   REFERENCES users (id),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_id) REFERENCES comments (id)
);

-- TODO(team): PK 형태 미정. 잠정으로 id PK + UNIQUE(post_id, user_id) (대안: 복합 PK)
CREATE TABLE post_likes (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint      NOT NULL,
    user_id    bigint      NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_post_likes_post_user UNIQUE (post_id, user_id),
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE post_view_events (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   uuid        NOT NULL,
    post_id    bigint      NOT NULL,
    user_id    bigint      NOT NULL,
    client_ts  timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_post_view_events_event_id UNIQUE (event_id),
    CONSTRAINT fk_post_view_events_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_post_view_events_user FOREIGN KEY (user_id) REFERENCES users (id)
);
