-- =====================================================================
-- baseline 스키마 (잠정)
-- TODO(team): anonymous_board_erd.html이 아직 반영되지 않았다. ERD 확정 시 baseline-v2로 올린다.
-- 기준: CLAUDE.md 잠정 스키마 (2회차 시드 표 + v3 초안의 users)
--
-- - PK는 bigint 시퀀스(GENERATED BY DEFAULT AS IDENTITY). event_id만 UUID.
--   시드가 id를 직접 넣었다면 적재 후 setval로 시퀀스를 맞춰야 한다.
-- - 카운터는 posts가 아니라 post_stats(1:1)에서 갱신한다.
-- - 이 파일에는 PK, UNIQUE(정합성 제약), FK만 둔다. 조회용 인덱스는 V2(db/migration-indexes)에 분리했다.
-- - TODO(team): FK 제약 포함 여부 미정. 잠정으로 포함한다 (README "팀 확인 필요").
-- =====================================================================

CREATE TABLE boards (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL
);

CREATE TABLE users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname   varchar(50) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE posts (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id   bigint       NOT NULL,
    author_id  bigint       NOT NULL,
    title      varchar(200) NOT NULL,
    content    text         NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_posts_board  FOREIGN KEY (board_id)  REFERENCES boards (id),
    CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES users (id)
);

-- posts와 1:1. 조회수와 좋아요 카운터는 여기서 UPDATE ... SET x = x + 1로 갱신한다 (핫 로우 경합을 일부러 둔다)
CREATE TABLE post_stats (
    post_id    bigint PRIMARY KEY,
    view_count bigint NOT NULL DEFAULT 0,
    like_count bigint NOT NULL DEFAULT 0,
    CONSTRAINT fk_post_stats_post FOREIGN KEY (post_id) REFERENCES posts (id)
);

CREATE TABLE comments (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint      NOT NULL,
    user_id    bigint      NOT NULL,
    content    text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- TODO(team): PK 형태 미정. 잠정으로 id PK + UNIQUE(post_id, user_id) (대안: 복합 PK)
CREATE TABLE post_likes (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint      NOT NULL,
    user_id    bigint      NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_post_likes_post_user UNIQUE (post_id, user_id),
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE post_view_events (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   uuid        NOT NULL,
    post_id    bigint      NOT NULL,
    user_id    bigint      NOT NULL,
    client_ts  timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_post_view_events_event_id UNIQUE (event_id),
    CONSTRAINT fk_post_view_events_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_post_view_events_user FOREIGN KEY (user_id) REFERENCES users (id)
);
